# ----
# Site

title: "regymm's toy shop"
url: "https://regymm.github.io"
baseurl: "/regymm-toy-shop"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /favicon.png
#description: Fur t-shirt store
author:
  name: regymm
  email: ustcymgu@gmail.com
  twitter: regymm0 # twitter username without the @ symbol
  #phone: "+1 23456789"
#social:
  #name: Fur Template
  #links:
    #- https://github.com/CloudCannon/fur-jekyll-template

# -----
# Build
#timezone: Etc/UTC

collections:
  staff_members:
    output: false
  products:
    output: true

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

#social_icons:
  #- Email
  #- Twitter
  #- RSS
  #- Facebook
  #- Google Plus
  #- Instagram
  #- LinkedIn
  #- Pinterest
  #- Tumblr
  #- YouTube
